sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - BUCKET=akerl-hookshot
  - secure: KfMumvHakZayxSOrTMiA3om9ubTXwyZWWHu/C591eaG4iCdNBux2GjQ/BLM58WspAM+c/HgIK9nGh2/4VuQjNXcamDkFvXAdlg2DrZeVVcfE47C9pDa9gYuepRi2aNXGMd7mHag1/Sl4YJwPZ1XekCi0FEy6NVHGBPt7v/mj2p/WsdXUpbhVjHLWXrsaGod6w2nedEs5jY5hNpm64emOEWBXBDUfMPSGxFjnMhDdhtb4lMG8wCn72S7iHXjficpOspJO/M/5evJolpB2vMTVt//8NP2X5w4oHuXDlr97VKGvPA+l5PkeDyW57LrBNqRBg9MGn+O8fNeBo0F/rmA1oCu2sRH7VhVHtxyqEzwlXfgAr5uDeXEqb4+vkc/EiUO/BKPFLdwIkO6O/fvbFb/gnbu1o6YOTugswaHDnJS66i09RCkELB+FVWgVwiWuPCLDXdpBVlgQGJI03Syl43vVKdVnTihflzFLtOF/9MZ0XIT4jOG8x6XwGrT7hzey73IqFWOk1EDyxJbRuTROgBEYLWhZO1+ULARGzpZQ/mFFah1OlWjcICO9no0mdXvuqFeJtFuJjVGZillvQjVDlOiGESltwtLMZmYRBTI27+ZuGmVhmBy4O0NWxGuFI1uviD7ZYL28+wdQeeLzhyJqpB9/HsEU0kYhyUYcDPaP+eMG24Q=
before_install:
- pip install --user awscli
script: make
deploy:
  provider: script
  script: make release && aws s3 cp pkg/payload.zip "s3://$BUCKET/lambdas/payload-$TRAVIS_TAG.zip"
    || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: RAd7QO/gf+1DdAIx+CuYrGdBTyeJ+lk3hM20v+hD7Bk0Dh0bQPQstsAvP+iMTsr2BbzkM+jiM7xMT22dmhfXYmIjo8tIGr9QzkEVwnClO61hN0C5iiJmhAQGmyS/eDQhrImMjA8iX5UdYNdQzBO0gWJ0AP93RG4tr3XebyENvP0SxeVYcR2Gs5rPXiPn9xXpiYypp4XxwBsuGGq8qZxCvcF6/RneWz0QuonWFsc2hU4mmq6Nlld6QFHSnAxG4t3leQbF/9LsxwmrXHCNOz+3mAOXpudNjc/24RLTBne0nqzOJjmul3yEjMeWNsWtB3MX9nyk0fd23Bgk5ACioKcmQH2CVzrWvtJWcBz1Liu/nYzs4U9NwXUXWcRV6lGMYygRXav/2jJtT66/am/JWmW39hFiqbIffyfgRZ+5b/rHbjsQA/OLEP4ZxUKOMe5PfkAABB0QO0x2BAfZK5FM1nJdRYHsMbU5xRT9AyOtOwM0F8hy933rNt+/hid6QoSYU1Hy2k1CxkJtT7fHpHtq9FmPS3oU8KMijlQaGbaaI+u5lCMqCHbUZyDX2qpdfcWK3mmWe8gcGTwMyog303+1fCPXEUmmaFSOpdjvhqBuJaveGDBm82yA9emSU4nx5nDMAAyfqprGHsyzLkATT4Rb9apgYNcvGOuC4h2wNyygXytkdXU=
